imports:
    - { resource: "@CFUserBundle/Resources/config/security.yml" }

security:
    role_hierarchy:
        ROLE_ADMIN:       
            - ROLE_USER
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN: 
            - ROLE_USER
            - ROLE_ADMIN
            - ROLE_SONATA_ADMIN

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil/voir/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil/, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }