imports:
    - { resource: "@CFUserBundle/Resources/config/security.yml" }

security:

    role_hierarchy:
        ROLE_ASSOCIATION: 
            - ROLE_USER
        ROLE_ENTREPRISE:  
            - ROLE_USER
        ROLE_BENEVOLE:    
            - ROLE_USER
        ROLE_ADMIN:       
            - ROLE_USER
            - ROLE_BENEVOLE
            - ROLE_ENTREPRISE
            - ROLE_ASSOCIATION
        ROLE_SUPER_ADMIN: 
            - ROLE_USER
            - ROLE_ADMIN
            - ROLE_BENEVOLE
            - ROLE_ENTREPRISE
            - ROLE_ASSOCIATION

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }