cf_conversation_list:
    path:     /liste
    defaults: { _controller: CFMessageBundle:Conversation:list }

cf_conversation_show:
    path:     /{id}
    defaults: { _controller: CFMessageBundle:Conversation:show }