<?php

namespace CF\MainBundle\Entity;

/**
 * ProjetAccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBoxsCroissant($projet) {
        $qb = $this->createQueryBuilder('b');
         
        $qb->where('b.projet = :projet')
           ->setParameter('projet', $projet)
           ->orderBy('b.ordre', 'ASC')
           ;
                 
        return $qb->getQuery()->getResult();
    }
}