<?php

namespace CF\MainBundle\Entity;

/**
 * ProjetAccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSearchList($motcle)
    {  
        $qb = $this->createQueryBuilder('p');
         
        $qb->join('p.idAsso', 'a')
        	->where('p.nom LIKE :motcle')
        	->orWhere('a.ville LIKE :motcle')
            ->setParameter('motcle', '%'.$motcle.'%');
                 
        return $qb->getQuery()->getResult();
    }
}