<?php

namespace CF\MainBundle\Entity;

/**
 * ProjetAccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
	public function getProjetsAboutissants()
    {  
        $qb = $this->createQueryBuilder('p');
         
        $qb->orderBy('p.dateFin', 'ASC')
           ->setMaxResults(10);
                 
        return $qb->getQuery()->getResult();
    }

    public function getProjetsNouveaux()
    {  
        $qb = $this->createQueryBuilder('p');
         
        $qb->orderBy('p.dateCreation', 'DESC')
           ->setMaxResults(10);
                 
        return $qb->getQuery()->getResult();
    }

	public function getSearchList($motcle)
    {  
        $qb = $this->createQueryBuilder('p');
         
        $qb->leftJoin('p.association', 'a')
            ->leftJoin('p.tags', 't')
        	->where('p.nom LIKE :motcle')
        	->orWhere('a.ville LIKE :motcle')
            ->orWhere('t.nom LIKE :motcle')
            ->setParameter('motcle', '%'.$motcle.'%');
                 
        return $qb->getQuery()->getResult();
    }

    public function getValidate()
    {
        $qb = $this->createQueryBuilder('p');
         
        $qb->where('p.valider = true');
                 
        return $qb->getQuery()->getResult();
    }
}