<?php

namespace CF\MainBundle\Entity;

/**
 * ProjetAccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetAccueilRepository extends \Doctrine\ORM\EntityRepository
{
}
