<?php

namespace CF\MainBundle\Entity;

/**
 * SelecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelecteurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSelecteursAccueil() {
        $qb = $this->createQueryBuilder('s');
         
        $qb->where('s.type = 1')
        	->orderBy('s.ordre', 'ASC')
           ;
                 
        return $qb->getQuery()->getResult();
    }

    public function getSelecteursLesProjets() {
        $qb = $this->createQueryBuilder('s');
         
        $qb->where('s.type = 2')
        	->orderBy('s.ordre', 'ASC')
           ;
                 
        return $qb->getQuery()->getResult();
    }
}
