<?php

namespace CF\UserBundle\Entity;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchNameList($search)
    {  
        $qb = $this->createQueryBuilder('a');
         
        $qb->where('a.nom LIKE :search')
           ->setParameter('search', '%'.$search.'%');
                 
        return $qb->getQuery()->getResult();
    }

    public function getSearchTagsList($tag)
    {  
        $qb = $this->createQueryBuilder('a');
         
        $qb->leftJoin('a.tags', 't')
           ->where('a.ville LIKE :tag OR t.nom LIKE :tag')
           ->setParameter('tag', '%'.$tag.'%');
                 
        return $qb->getQuery()->getResult();
    }
}