cf_site_commentcamarche:
    path:     /comment-ca-marche
    defaults: { _controller: CFSiteBundle:Pages:commentcamarche }

cf_site_partenaires:
    path:     /partenaires
    defaults: { _controller: CFSiteBundle:Pages:partenaires }

cf_site_contact:
    path:     /contact
    defaults: { _controller: CFSiteBundle:Pages:contact }

cf_site_developpeurs:
    path:     /developpeurs
    defaults: { _controller: CFSiteBundle:Pages:developpeurs }

cf_site_conditions:
    path:     /conditions
    defaults: { _controller: CFSiteBundle:Pages:conditions }

cf_site_apropos:
    path:     /a-propos
    defaults: { _controller: CFSiteBundle:Pages:apropos }