<?php

namespace CF\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	public function findUserNotification($user)
	{
		return $this->createQueryBuilder('n')
			->join('n.user', 'u')
			->where('u = :user')
			->setParameter('user', $user)
			->andWhere('n.vu < 1')
			->orderBy('n.id', 'DESC')
			->setMaxResults(50)
			->getQuery()
			->getResult();
	}

	public function getProjetsEnCours($user)
	{
		return $this->createQueryBuilder('n')
			->where('n.type = 2')
			->andWhere('n.vu < 1')
			->getQuery()
			->getResult();
	}

	public function getMessages($user)
	{
		return $this->createQueryBuilder('n')
			->where('n.type = 1')
			->andWhere('n.vu < 1')
			->getQuery()
			->getResult();
	}

	public function getNotificationsByUser($user)
	{
		return $this->createQueryBuilder('n')
			->where('n.vu = 0')
			->andWhere('n.user = :user')
			->setParameter('user', $user)
			->orderBy('n.id', 'DESC')
			->getQuery()
			->getResult();
	}
}
