services:
    sonata.admin.association:
        class: CF\UserBundle\Admin\AssociationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Association" }
        arguments:
            - ~
            - CF\UserBundle\Entity\Association
            - ~
        calls:
            - [ setTranslationDomain, [CFUserBundle]]
    sonata.admin.particulier:
        class: CF\UserBundle\Admin\ParticulierAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Particulier" }
        arguments:
            - ~
            - CF\UserBundle\Entity\Particulier
            - ~
        calls:
            - [ setTranslationDomain, [CFUserBundle]]
    sonata.admin.entreprise:
        class: CF\UserBundle\Admin\EntrepriseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Entreprise" }
        arguments:
            - ~
            - CF\UserBundle\Entity\Entreprise
            - ~
        calls:
            - [ setTranslationDomain, [CFUserBundle]]