security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                use_forward: false
                check_path: fos_user_security_check
                failure_path: null
                default_target_path: /
                remember_me: true
            remember_me:
                key: %secret%
                lifetime: 30000000
                path: /
                domain: ~
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true